### ISSUE TITLE
Flycheck overlays are not displayed.

### ISSUE THREAD

**Issue by baol** [dengste/minimap#13]
A major plus of a minimap to me is being able to have an overview of errors, warnings, fixmes, and todos.

At the moment the error highlighted by flycheck are not displayed into the minibar unless I explicitely do a M-x minibar-sync-overlays (and are not update afterwards unless the command is repeated).

Is this a know issue/limitation?

**Comment by dengste** [comment]
Unfortunately, this stuff cannot be automated for every package, you need to call minimap-sync-overlays from some hook. I've added this now for flycheck.
