### ISSUE TITLE
Warnings on installation

### ISSUE THREAD

**Issue by johnjcamilleri** [dengste/minimap#4]
Trying to install minimap from elpa, I get these warnings in my compile log:

```
Leaving directory `/Users/john/.emacs.d/elpa/minimap-1.2'

Compiling file /Users/john/.emacs.d/elpa/minimap-1.2/minimap-pkg.el at Fri Oct 10 09:02:08 2014
Entering directory `/Users/john/.emacs.d/elpa/minimap-1.2/'

Compiling file /Users/john/.emacs.d/elpa/minimap-1.2/minimap.el at Fri Oct 10 09:02:08 2014

In end of data:
minimap.el:905:1:Warning: the following functions are not known to be defined:
    semantic-active-p, semantic-fetch-tags, semantic-tag-class,
    semantic-tag-overlay, semantic-tag-name
```

`M-x minimap-mode` in general works, but setting some variables such as `minimap-hide-fringes t` and `minimap-highlight-line nil` doesn't seem to have any effect.

I'm using `GNU Emacs 24.3.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2013-03-13 on bob.porkrind.org` on OSX 10.9.5.

**Comment by dengste** [comment]
I've silenced the warnings and fixed minimap-hide-fringes. minimap-highlight-line works for me as expected, though.
